### ISSUE TITLE
continual prediction possible?

### ISSUE THREAD

**Issue by AlconDivino** [huseinzol05/Stock-Prediction-Models#10]
Is it possible to feed the Prediction function more close prices and make continual predictions? Or does the Model need to be trained again every time new data is available?

**Comment by huseinzol05** [comment]
I never tested this before. I just retrain it again. Maybe you can try?

**Comment by huseinzol05** [comment]
I also use this model on production for crypto. We cached various of pairs and exchanges, so we use apache airflow to do training scheduling and save it in database.

**Comment by bitnom** [comment]
> I also use this model on production for crypto. We cached various of pairs and exchanges, so we use apache airflow to do training scheduling and save it in database.

You have code to save checkpoints?

**Comment by huseinzol05** [comment]
I use pickle. not a problem.

**Comment by ramonqu7** [comment]
I tried to save the model, but got this error: can't pickle _thread.RLock objects
can you help me with this?
