### ISSUE TITLE
How to use this project as a non-ML guy?

### ISSUE THREAD

**Issue by vital987** [huseinzol05/Stock-Prediction-Models#107]
Hi, I want to use this project for the purpose it's made for, can anyone describe me the usage steps and meaning of the **folder names** present in the project? I know python but in **Cloud Computing** field.

**Comment by liketop** [comment]
Maybe a bit late but: https://github.com/huseinzol05/Stock-Prediction-Models/tree/master/stock-forecasting-js

**Comment by vital987** [comment]
> Maybe a bit late but: https://github.com/huseinzol05/Stock-Prediction-Models/tree/master/stock-forecasting-js

I used it, thanks for the help :)
