### ISSUE TITLE
which-stock.ipynb

### ISSUE THREAD

**Issue by GirishKumarSharma** [huseinzol05/Stock-Prediction-Models#119]
I just git clone and run the ipnyb and got stuck in the last input.

`TypeError                                 Traceback (most recent call last)`
`Input In [10], in <cell line: 1>()`
`----> 1 g = sns.jointplot("volatility", "returns", data=combine, kind="reg",height=7)`
`      3 for i in range(combine.shape[0]):`
`      4     plt.annotate(ori_name[i].replace('.csv',''), (combine.iloc[i, 1], combine.iloc[i, 0]))`
``
`TypeError: jointplot() got multiple values for argument 'data'`

**Comment by nil-andreu** [comment]
Heey!
Try to define the parameters of the function: `sns.jointplot(data=combine, x='volatility', y='returns', kind='reg', height=7)`.

**Comment by GirishKumarSharma** [comment]
Thanks! It worked. Now testing other files.

**Comment by nil-andreu** [comment]
Anything else let me know @GirishKumarSharma  !
