### ISSUE TITLE
Training On Intraday

### ISSUE THREAD

**Issue by bitnom** [huseinzol05/Stock-Prediction-Models#12]
Does the data just need to be further fit for intraday? I haven't looked into it yet but I know it causes an error.

**Comment by AlconDivino** [comment]
I tested it on data without time series (BTC-USDT binance data 1hr timeframe 1.1.2018 till today) in ran very profitable without any problems

**Comment by bitnom** [comment]
> I tested it on data without time series (BTC-USDT binance data 1hr timeframe 1.1.2018 till today) in ran very profitable without any problems

By "Without time series" do you mean you removed the time of day from the string?

**Comment by AlconDivino** [comment]
I only had the columns Open , High, Low ,Close , Volume in my CSV file
I gathered the Data with an extern programm and did not include the time , because binance gives you the timestamp in ms not any date 

Also i think the code doesn't care about time at all because the only data that is used is an list of Close Prices. So i think it doesn't care about time it just iterates through the list and prints one iteration as day.

**Comment by munkh-erdene** [comment]
First of thank you for sharing, how can i predict next day? Just one action?

**Comment by huseinzol05** [comment]
@munkh-erdene if you want to predict next day or future, first you need to predict the trend, you can use any deep learning model you want, I included in this repo.
Predict trend using LSTM -> predict buy and sell using NES

**Comment by huseinzol05** [comment]
@TensorTom the model doesnt care about the timestamp, you can gibe every second, every minute, every 5 minutes, it doesnt care. As long it is still a trend.

**Comment by AlconDivino** [comment]
@huseinzol05  could you add a notebook with an example using for example the lstm module and the evolution-bayesian-strategy?

**Comment by augmen** [comment]
@huseinzol05  where is the repo for Predict trend using LSTM -> predict buy and sell using NES. I need to predict the next day or future .

**Comment by augmen** [comment]
@huseinzol05 how to make the evolution agent to fetch data in real time and trade in real stock market.
