### ISSUE TITLE
More Dimensions

### ISSUE THREAD

**Issue by bitnom** [huseinzol05/Stock-Prediction-Models#13]
When you have time and are back to coding here, please consider trying to use more than just the close price. We should use the full OHLCV as well as 5 day MA, 50 day MA, and possibly VWAP. Currently, model is only using closing price. I will work at this as well. I have some custom indicators as well (It's a specialty of mine).

Obviously don't want too many dimensions but adding some should improve the score.

**Comment by AlconDivino** [comment]
So basically make it possible to pass an array of values to the algo, not only a list

**Comment by huseinzol05** [comment]
Yes of course can done it, I will add new notebook for that, thanks!

**Comment by AlconDivino** [comment]
Any progress? Or could you tell me what parts must be changed to Archive this?

**Comment by huseinzol05** [comment]
https://github.com/huseinzol05/Stock-Prediction-Models/blob/master/realtime-agent/agent.ipynb

Check on block 5, I use `Close` and `Volume`.
