### ISSUE TITLE
cannot convert float NaN to integer" error

### ISSUE THREAD

**Issue by ghost** [huseinzol05/Stock-Prediction-Models#16]
the code starts to give  "cannot convert float NaN to integer" errors in some pairs ( it does profit in pairs that it works). I still cannot find the exact reason for it.

**Comment by bitnom** [comment]
> After testing Evolution_Bayesian.py in several cryptocurrencies I see that it profits (or seems to profit) almost all the time. I want to use it as a model of a custom bot that runs on binance and I am looking for someone to collaborate with me. I said "seems to profit" because when I apply it for cumulative returns with commissions such as starting with 100 dollars and buying/selling with all units every time rather than min/max 5 units, the code starts to give "cannot convert float NaN to integer" errors in some pairs ( it does profit in pairs that it works). I still cannot find the exact reason for it. I also need to colloborate on using the timesteps right and choosing the optimal buy/sell points in backtesting/live trading.

Are you removing the time from the date strings? You have to do that.

**Comment by ghost** [comment]
I am using daily data most of the time since it tends to crash with prices less than zero so I don't compare it with BTC pairs(binance). Just happened with BAT-USD didn't change anything rather than dataset, below was the data. but I know that the same BAT data worked last week. It also worked with NEO, ETH data I got from same place(yahoo). I've been experimenting in this repo almost for a month, it just happens randomly and still cannot figure it out.
By the way in another issue I've read that you do use this code as a model in a live environment. Does it work fine?

```
Date,Open,High,Low,Close,Adj Close,Volume
2017-05-31,0.234000,0.289300,0.130300,0.165600,0.165600,448412
2017-06-01,0.171100,0.188500,0.149500,0.155500,0.155500,907879
2017-06-02,0.158800,0.185800,0.152700,0.165200,0.165200,1189545
2017-06-03,0.163800,0.367000,0.162400,0.284700,0.284700,18233470
```

this is the trace
```

Search parameters {'window_size': 28, 'skip': 15, 'population_size': 50, 'sigma': 0.99, 'learning_rate': 1e-06, 'size_network': 137}
time taken to train: 3.249074935913086 seconds
stop after 100 iteration with investment 0.000000
|  246      |  0.0      |  1e-06    |  50.0     |  0.99     |  137.3    |  15.0     |  28.05    |

Search parameters {'window_size': 2, 'skip': 1, 'population_size': 1, 'sigma': 0.01, 'learning_rate': 0.49, 'size_network': 445}
Evolution_Bayesian.py:66: RuntimeWarning: invalid value encountered in true_divide
  rewards = (rewards - np.mean(rewards)) / np.std(rewards)
stop after 100 iteration with investment 0.000000
|  247      |  0.0      |  0.49     |  1.0      |  0.01     |  444.5    |  1.0      |  2.0      |

Search parameters {'window_size': 50, 'skip': 1, 'population_size': 50, 'sigma': 0.99, 'learning_rate': 0.49, 'size_network': 255}
time taken to train: 95.16062211990356 seconds
stop after 100 iteration with investment 0.000000
|  248      |  0.0      |  0.49     |  50.0     |  0.99     |  255.2    |  1.0      |  50.0     |

Search parameters {'window_size': 2, 'skip': 1, 'population_size': 28, 'sigma': 0.01, 'learning_rate': 1e-06, 'size_network': 317}
Evolution_Bayesian.py:66: RuntimeWarning: invalid value encountered in true_divide
  rewards = (rewards - np.mean(rewards)) / np.std(rewards)
stop after 100 iteration with investment 0.000000
|  249      |  0.0      |  1e-06    |  27.91    |  0.01     |  317.2    |  1.0      |  2.0      |

Search parameters {'window_size': 18, 'skip': 15, 'population_size': 34, 'sigma': 0.01, 'learning_rate': 0.49, 'size_network': 628}
Evolution_Bayesian.py:66: RuntimeWarning: invalid value encountered in true_divide
  rewards = (rewards - np.mean(rewards)) / np.std(rewards)
stop after 100 iteration with investment 0.000000
|  250      |  0.0      |  0.49     |  34.42    |  0.01     |  628.3    |  15.0     |  17.67    |
=================================================================================================
----------------------------------------------
{'target': 0.005529999999998836, 'params': {'learning_rate': 0.07725429450379967, 'population_size': 27.42513865462102, 'sigma': 0.3545970562206382, 'size_network': 539.0312796221687, 'skip': 3.221331899516282, 'window_size': 13.424744381086434}}
Traceback (most recent call last):
  File "Evolution_Bayesian.py", line 325, in <module>
    agent.fit(500, 100)
  File "Evolution_Bayesian.py", line 172, in fit
    self.es.train(iterations, print_every = checkpoint)
  File "Evolution_Bayesian.py", line 65, in train
    rewards[k] = self.reward_function(weights_population)
  File "Evolution_Bayesian.py", line 146, in get_reward
    action, buy = self.act(state)
  File "Evolution_Bayesian.py", line 136, in act
    return np.argmax(decision[0]), int(buy[0])
ValueError: cannot convert float NaN to integer
```

**Comment by AlconDivino** [comment]
I do encounter the same problem, although upon rerunning the whole script i don't get the error. I still don't know what is the reason for this

I have the same plan tbh wanna work together?

**Comment by ghost** [comment]
I want to work together. Could you add me on telegram @canercak

**Comment by bitnom** [comment]
I think I fixed this some days ago with:

```
def act(self, sequence):
        decision, buy = self.model.predict(np.array(sequence))
        return np.argmax(decision[0]), round(buy[0][0]).astype(int)
```
noting **astype(int)**
I'm going from memory. Will l look closely again when I have more time.

**Comment by vedantk281007** [comment]
> I think I fixed this some days ago with:
> 
> ```
> def act(self, sequence):
>         decision, buy = self.model.predict(np.array(sequence))
>         return np.argmax(decision[0]), round(buy[0][0]).astype(int)
> ```
> 
> noting **astype(int)** I'm going from memory. Will l look closely again when I have more time.

Hi, after trying this, I am getting the error:
```
AttributeError: 'int' object has no attribute 'astype'
```

Please help @bitnom @huseinzol05
