### ISSUE TITLE
same data train and test for agent/6.evolution-strategy-agent.ipynb

### ISSUE THREAD

**Issue by ghost** [huseinzol05/Stock-Prediction-Models#26]
hi, i am new to this area and i don't understand how the data used for train and test in agent/6.evolution-strategy-agent, as i know the train and test data set should be different.

But it seem that the agent train the whole data `agent.fit(iterations = 500, checkpoint = 10)` and predict the action for each day in func `def buy(self)`.

Is that mean the model already know the whole data and predict the data? thx :D

**Comment by huseinzol05** [comment]
Yes.

**Comment by huseinzol05** [comment]
You might want to check this, https://github.com/huseinzol05/Stock-Prediction-Models/tree/master/realtime-agent

**Comment by r-matsuzaka** [comment]
@huseinzol05 
Thank you for sharing great work.
I have a question about your training concept.
Why do you use the same dataset for prediction?
I think data should be separated into train, val and test.
