### ISSUE TITLE
How to forecast into future evolution-strategy-bayesian-agent?

### ISSUE THREAD

**Issue by JeanLoriston** [huseinzol05/Stock-Prediction-Models#28]
Hi this is really impressive and useful for me because i am new to all this. My question is how can i get the bayesian agent to predict into the future for example using past data make a forecast of where for it to buy and sell  for example make it give a prediction a few days in the future. i have a python script that performs crpto  trading   and i would like to use predictions from this model to enhance it

**Comment by huseinzol05** [comment]
https://github.com/huseinzol05/Stock-Prediction-Models/tree/master/realtime-agent

You might want to train the agent on different pairs you have.

**Comment by JeanLoriston** [comment]
@huseinzol05 Thank you so much ! i been desperately looking for something like this for weeks
also the instructions say Run app.py to serve the checkpoint model using Flask in the app.py i  see it uses agent.pkl

**Comment by JeanLoriston** [comment]
in the agent.ipynb I don't see anything to save a .pkl file how can i do that? or how can i get each individual variable that stores buy ,price, total balance and pass that into flask instead?

**Comment by huseinzol05** [comment]
Fixed the issue about saving `agent.pkl`. Can you provide some line of codes about `or how can i get each individual variable that stores buy ,price, total balance and pass that into flask instead`.

**Comment by JeanLoriston** [comment]
@huseinzol05  Thank you!!! now i can try to figure out how to create a realtime bayesian optimization agent with arima or other model for next day forecast predictions thank you so much  for your work. i don't know how well ill get it done but if you can consider making that type of agent it would help me out tremendously.

**Comment by yeah-me** [comment]
> 
> 
> @huseinzol05 Thank you!!! now i can try to figure out how to create a realtime bayesian optimization agent with arima or other model for next day forecast predictions thank you so much for your work. i don't know how well ill get it done but if you can consider making that type of agent it would help me out tremendously.

How is it going with your project? did you make it work? What technologies and libs did you use?
