### ISSUE TITLE
is there sth wrong about batch_y ?

### ISSUE THREAD

**Issue by gloddream** [huseinzol05/Stock-Prediction-Models#29]
`batch_x = np.expand_dims(
            df_log.iloc[k : index, :].values, axis = 0
        ) `
 `batch_y = df_log.iloc[k + 1 : index + 1, :].values
`

the shape of batch_y should be (1, output_size). 
but in the code is (timestamp, output_size)

**Comment by huseinzol05** [comment]
Can you share which notebook?
