### ISSUE TITLE
How can I use a different model for realtime agent?

### ISSUE THREAD

**Issue by JeanLoriston** [huseinzol05/Stock-Prediction-Models#30]
For the realtime agent i am trying to add evolution-strategy-bayesian-agent  how would i do that? i tried rewriting and changing lots of parts in the realtime agent and i am stuck with errors and not any clear way to do it please if i can get  example code it would will help or what exactly to change to make it work?
also in the scriot what do these variables mean?
. Capitial = I guess  how much money you have?
. inventory_size = I guess How much stock to trade?
. mean_inventory = ?
i am not sure what they mean

**Comment by huseinzol05** [comment]
`Capital = I guess how much money you have`, yes.
`inventory_size = I guess How much stock to trade`, I want the model also check the size of inventory as one of parameters.
`mean_inventory = bought prices`, I want the model also check historical bought prices as one of parameters.

**Comment by JeanLoriston** [comment]
Ok thank you
