### ISSUE TITLE
Neuroevolution Model Saving.

### ISSUE THREAD

**Issue by vithalpatil** [huseinzol05/Stock-Prediction-Models#32]
Hi,

How do I save the trained Neuroevolution model and reuse it? [agent/21.neuro-evolution-agent.ipynb](https://github.com/huseinzol05/Stock-Prediction-Models/blob/master/agent/21.neuro-evolution-agent.ipynb)

**Comment by maxwell211** [comment]
same question

**Comment by JeanLoriston** [comment]
You can save it using pickle 
https://github.com/huseinzol05/Stock-Prediction-Models/issues/2#issuecomment-451172546
