### ISSUE TITLE
Shape Not aligned error  realtime agent app.py

### ISSUE THREAD

**Issue by JeanLoriston** [huseinzol05/Stock-Prediction-Models#34]
When I run app.py from the realtime using  the realtime-evolution-strategy.ipynb  i get this error how can I fix it? 

feed = np.dot(inputs, self.weights[0]) + self.weights[-2]
ValueError: shapes (1,79) and (399,500) not aligned: 79 (dim 1) != 399 (dim 0)

**Comment by huseinzol05** [comment]
Your input size during training and deploy are not same. you should check the window size.

**Comment by JeanLoriston** [comment]
k thanks
