### ISSUE TITLE
Predict next day closing price (stack-encoder-ensemble-xgb.ipynb)

### ISSUE THREAD

**Issue by andrei297** [huseinzol05/Stock-Prediction-Models#39]
Maybe it's a newbie question but how do I predict the next day closing price and print the output? By "predict the next day closing price" I mean the closing price in the future, outside the training data, say I have the trading data with the last date 10 July 2019, how do I get the predicted closing price for 11 July 2019?

Any help is greatly appreciated!
Thanks

PS: Amazing work!

**Comment by huseinzol05** [comment]
`stack-encoder-ensemble-xgb.ipynb` is not a good model, you might want to use deep learning models. In deep learning examples, I already show how to predict 3 months ahead, you can run `t + N` ahead in your local.

**Comment by andrei297** [comment]
Thanks huseinzol05, I appreciate it.
Any particular models under deep learning examples that you consider to be better than the rest? I'll test a few tomorrow but just by looking at the notebooks some seem to perform better. Also have you considered instead of predicting the exact prices to predict a binary output (1, 0) , 1=price is up 0=price down, and calculate the accuracy for a particular model?

Anyway thanks again!

**Comment by huseinzol05** [comment]
You can try, or also can calculate percentage mean error.
