### ISSUE TITLE
dates in plot

### ISSUE THREAD

**Issue by HomunculusK** [huseinzol05/Stock-Prediction-Models#40]
I was trying deep learning models but I always get duplicated dates and couldn't figure out why, any idea is welcome 👍 

![Screenshot_3](https://user-images.githubusercontent.com/18039387/61209477-8c78a200-a702-11e9-9494-ac409c366cd3.png)

**Comment by huseinzol05** [comment]
You can skip it like this,
```
plt.xticks(
        np.arange(len(timestamp))[::5], timestamp[::5], rotation = '45', ha = 'right'
    )
```
