### ISSUE TITLE
Stuck in evolution-strategy agent when the price is small

### ISSUE THREAD

**Issue by soulaw-mkii** [huseinzol05/Stock-Prediction-Models#44]
Hi Husein,

I am trying to swap the data source from stock to Forex price. When I train the model, the reward keep zeros.

`iter 10. reward: 0.000000`
`iter 20. reward: 0.000000`
`iter 30. reward: 0.000000`
`:`

Then I did some experiment:
1  magnify FX close price by 10000, the training resumes normal
2. use TSLA close price divided by 1000 and the reward stuck to zero

It looks to me if the price is small, training will stuck. Do you have idea why it is?

Regards,
Steve

**Comment by huseinzol05** [comment]
the changes are too small during feed-forward, so the neural network not able to learn anything. Scaling is very important.

**Comment by soulaw-mkii** [comment]
Thanks for the prompt reply.  = D
