### ISSUE TITLE
app.py without flask 

### ISSUE THREAD

**Issue by augmen** [huseinzol05/Stock-Prediction-Models#45]
i don't need flask. what the code list function to be added to make the code run on  live markets agent.buy() or ages.trade(data) ? 
Also part from buy and sell call API whether we need to connect other data webnbsockets to the app.py if yes. plz guide which one and how ?
@huseinzol05

**Comment by huseinzol05** [comment]
I believe you need to find a python developer to help you this kind of problem. I can't provide all the solutions because you just required to do small changes on the code to make it works.

**Comment by augmen** [comment]
i have hired one . still  curious on which is the final execution command for app.py agent.buy() or agent.trade(data). 

If we can feed json data to agent.trade(data) fro request.ipynb then why there is line 347 app.py we have :

df = pd.read_csv('TWTR.csv') real_trend = df['Close'].tolist() parameters = [df['Close'].tolist(), df['Volume'].tolist()] minmax = MinMaxScaler(feature_range = (100, 200)).fit(np.array(parameters).T) scaled_parameters = minmax.transform(np.array(parameters).T).T.tolist() initial_money = np.max(parameters[0]) * 2
why we need to feed again this data in app.py ?

plz guide @huseinzol05
