### ISSUE TITLE
predictions

### ISSUE THREAD

**Issue by ghost** [huseinzol05/Stock-Prediction-Models#46]
Hi  Thanks for sharing your codes, they provide good examples to get started with.   Could you help clarify my thinking on some of these examples.  For example the stack-encoder-ensemble-xgb case seems to show rather impressive ability to predict, however the entire data set is being used for many operations.  If that is correct then where is the predictive capability.  Are these examples just showing a better curve fitting method ?  I'm new to this field and could be way off in my initial interpretation...

**Comment by huseinzol05** [comment]
`stack-encoder-ensemble-xgb` is not good, lol. Use deep learning model. Some of it got better curve fitting, some are not, I just implementing some research papers.
