### ISSUE TITLE
Getting Unimplemented: TensorArray has size zero error while using my data

### ISSUE THREAD

**Issue by joyjitchatterjee** [huseinzol05/Stock-Prediction-Models#48]
Thank you for an amazing repo. However, when I am trying to use the Deep Learning 1 (LSTM) syntax in your repo with my own data (not related to stock markets but with a similar structure in a data frame), I get the following error:-
```
UnimplementedError: 2 root error(s) found.
  (0) Unimplemented: TensorArray has size zero, but element shape [?,128] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[{{node rnn/TensorArrayStack/TensorArrayGatherV3}}]]
  (1) Unimplemented: TensorArray has size zero, but element shape [?,128] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[{{node rnn/TensorArrayStack/TensorArrayGatherV3}}]]
	 [[dense/BiasAdd/_39]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

UnimplementedError                        Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1368           pass
   1369       message = error_interpolation.interpolate(message, self._graph)
-> 1370       raise type(e)(node_def, op, message)
   1371 
   1372   def _extend_graph(self):

UnimplementedError: 2 root error(s) found.
  (0) Unimplemented: TensorArray has size zero, but element shape [?,128] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[node rnn/TensorArrayStack/TensorArrayGatherV3 (defined at <ipython-input-117-2e6c344df6fd>:27) ]]
  (1) Unimplemented: TensorArray has size zero, but element shape [?,128] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[node rnn/TensorArrayStack/TensorArrayGatherV3 (defined at <ipython-input-117-2e6c344df6fd>:27) ]]
	 [[dense/BiasAdd/_39]]
0 successful operations.
0 derived errors ignored.
```
The model trains fine, but after training the problem arises in the output_predict cell part of the code. Everything runs smoothly until this error occurs. If you can please clarify and suggest what may be going wrong, it would be much appreciated. I checked SO and other resources for this error but still cannot figure out why the model fails. Thanks!

**Comment by joyjitchatterjee** [comment]
**UPDATE**
The Deep Learning 1 LSTM notebook works perfectly fine when the data has only 24 rows (as in the GOOG dataset used in this repo), however, when the number of rows is increased, say even a single 25th row, then this error occurs and the model isn't able to run. Have tested this on both CPU & GPU but the problem persists. Any suggestions on why the model isn't able to accept more than 24 rows please? Cheers

**Comment by huseinzol05** [comment]
I know this error since I created that notebook, lol. Alright, I will fix it. Thats because your input is an empty array.

**Comment by joyjitchatterjee** [comment]
@huseinzol05 thank you very much for the reply. I really would love to use this for my research project, and am glad to cite it in my repo too. If you can fix this at your earliest convenience, it would be much appreciated. Cheers

**Comment by huseinzol05** [comment]
Herm, I try to reproduce the error, but I cant get it. Can you share your dataset here, thanks!
