### ISSUE TITLE
What is the role of learned_position_encoding method in Attention is All You Need Notebook?

### ISSUE THREAD

**Issue by joyjitchatterjee** [huseinzol05/Stock-Prediction-Models#49]
Hi,
Great work on the attention is all you need repo. However, I am confused as to `learned_position_encoding()` is defined, but never used in the notebook? Other than this, the problem is that the model only works with the parameters used by you (timestamp=5,future_day=50). If I change timestamp or future day to any other value (e.g. timestamp=4), I get the error 
```
---> 18 df_log.loc[df_log.shape[0]] = out_logits[-1, :]
IndexError: index -1 is out of bounds for axis 0 with size 0
```
As per my understanding, this problem is happening in all the deep-learning notebooks. Other than this, the second issue I already created _Getting Unimplemented: TensorArray has size zero error while using my data _ #48 (https://github.com/huseinzol05/Stock-Prediction-Models/issues/48) is a bit confusing. Can you suggest or commit a work around on this please? Other than this, everything is really good and the models provide good results. Cheers.

**Comment by huseinzol05** [comment]
I improve the source code and do some repo refactor, https://github.com/huseinzol05/Stock-Prediction-Models/blob/master/deep-learning/16.attention-is-all-you-need.ipynb

I use `sinusoidal_position_encoding`, this might can help you, https://stackoverflow.com/questions/46452020/sinusoidal-embedding-attention-is-all-you-need
