### ISSUE TITLE
Accuracy Failure

### ISSUE THREAD

**Issue by bitnom** [huseinzol05/Stock-Prediction-Models#5]
I got the script running by using Pipenv. Please see [this readme](https://github.com/TensorTom/Stock-Prediction-Models/blob/master/agent/README_Pipenv.md) and [the Pipfile](https://github.com/TensorTom/Stock-Prediction-Models/blob/master/agent/Pipfile) I made. The problem now is that I'm getting:

**Best AGENT accuracy value: 3.244000**

Is this because I am training on the [GOOG.csv](https://github.com/TensorTom/Stock-Prediction-Models/blob/master/dataset/GOOG.csv) dataset? The Tesla file you used is not included in the repo. I'm wondering what the difference is and why I got low accuracy.

thanks

**Comment by huseinzol05** [comment]
Herm, I am not really sure about this, I am going to commit this repository after I done committed with my company repositories ya

**Comment by huseinzol05** [comment]
Oh, you trained on Google trend but predict on Tesla trend. Ya, you can't. the model doesn't have a good generalization between two different trends. It need to train real time, if trained on Google, it only can predict on Google.

Maybe you can try to train more than 10 different trends, and try to predict 11th trend, let see how is good the model generalization. Never tested this theory. Problem with reinforcement learning, let say the agent trained to play DOOM shooting game. After that you put the agent on different shooting game, counter strike. Even both are shooting game, but the agent never learn how to adapt inside counter strike environment. I never saw a reinforcement learning agent able to adapt different environment to test in any research papers, correct me if I am wrong, cited with paper link.

**Comment by AlconDivino** [comment]
I recommend using the GOOG-year.csv file as data. The GOOG.csv file has only 24 daily close prices i think its not strange to see failure in accuracy there

**Comment by TensorTom** [comment]
I tried to start passing them but how did I mess up the shape? https://github.com/huseinzol05/Stock-Prediction-Models/issues/7

**Comment by bitnom** [comment]
> Oh, you trained on Google trend but predict on Tesla trend. Ya, you can't. the model doesn't have a good generalization between two different trends. It need to train real time, if trained on Google, it only can predict on Google.
> 
> Maybe you can try to train more than 10 different trends, and try to predict 11th trend, let see how is good the model generalization. Never tested this theory. Problem with reinforcement learning, let say the agent trained to play DOOM shooting game. After that you put the agent on different shooting game, counter strike. Even both are shooting game, but the agent never learn how to adapt inside counter strike environment. I never saw a reinforcement learning agent able to adapt different environment to test in any research papers, correct me if I am wrong, cited with paper link.

I tried to pass them but how did I mess up the shape? https://github.com/huseinzol05/Stock-Prediction-Models/issues/7

**Comment by bitnom** [comment]
> Oh, you trained on Google trend but predict on Tesla trend. Ya, you can't. the model doesn't have a good generalization between two different trends. It need to train real time, if trained on Google, it only can predict on Google.
> 
> Maybe you can try to train more than 10 different trends, and try to predict 11th trend, let see how is good the model generalization. Never tested this theory. Problem with reinforcement learning, let say the agent trained to play DOOM shooting game. After that you put the agent on different shooting game, counter strike. Even both are shooting game, but the agent never learn how to adapt inside counter strike environment. I never saw a reinforcement learning agent able to adapt different environment to test in any research papers, correct me if I am wrong, cited with paper link.

Finally got it working with the yearly and am passing the outputs automatically: https://github.com/TensorTom/Stock-Prediction-Models/blob/master/agent/evolution-strategy-bayesian-agent.ipynb
