### ISSUE TITLE
Citations Needed

### ISSUE THREAD

**Issue by firmai** [huseinzol05/Stock-Prediction-Models#52]
Hi while we are at it, you have note cited the original creators of these models, that is a loss to them too. You simply collect an reapply it in a finance domain,  that does not absolve you from citation. By merely changing the name of these models, you don't suddenly become the owner of them.

**Comment by huseinzol05** [comment]
I believe you misunderstood something, 
1. I do not change any names here?
2. All those not my models, some might (hybrid between different models to increase comparison size), and all those models originally not for this kind of domain. Plus I do not use the original models from the papers, if yes, I included at starting of the code like DNC `copyright`, and also original link in README. Plus, those models are abstract models, so we need to create our own pipes and data to make those models applicable in this domain, means, new novelty. If I write a research paper regarding meta / application, sure will do, it is obvious, will citing them about the idea of the models.

If I copy literally someone code and use same methods on same domain (and fixed some software issues like deprecated issue and slightly improvement), I attached the links, like here I did, https://github.com/huseinzol05/Stock-Prediction-Models#simulations
Also, https://github.com/huseinzol05/NLP-Models-Tensorflow#abstractive-summarization

Also, posted `thank you` for the code, https://github.com/xueyouluo/my_seq2seq/issues/8

I am really sorry if you feel bad after I posted that issue, it just, well at least small citation already enough for me.

**Comment by firmai** [comment]
Okay sorry, you are right, and this is very nice of you. "Also, posted thank you for the code, xueyouluo/my_seq2seq#8". I guess what I am trying to say is that these software is there to better the community regardless of ownership. I have never taken a single cent or required anyone to cite any of my work. Once I update my work in November I will give you another shout out.
