### ISSUE TITLE
Bitcoin_Analysis_LSTM

### ISSUE THREAD

**Issue by HafsaaOuifak** [huseinzol05/Stock-Prediction-Models#59]

**Comment by huseinzol05** [comment]
Sorry, can you give link to the file? thanks

**Comment by HafsaaOuifak** [comment]
Yes of course, here the link : https://github.com/huseinzol05/Stock-Prediction-Models/blob/master/misc/bitcoin-analysis-lstm.ipynb

**Comment by huseinzol05** [comment]
the value of `sensitivity` is between 0-1, if near to 1, the model is very confidence with the result, vice versa.

**Comment by HafsaaOuifak** [comment]
please i need more clarification... How this sensitivity is calculated ? and for the tweet_volume ? we want to see the impact of tweeter prices on BTC or what exactly ?

**Comment by huseinzol05** [comment]
herm, I got the dataset from here, https://www.kaggle.com/paul92s/bitcoin-tweets-14m

I really cannot explain it, but, if you use sentiment / emotion data from here, https://doc.api.bitcurate.com/, I can explain it.
