### ISSUE TITLE
I can not import model in line 11 (stack-rnn-arima-xgb.ipynb).

### ISSUE THREAD

**Issue by dhaopku** [huseinzol05/Stock-Prediction-Models#6]
Dear husein，
In the （https://github.com/huseinzol05/Stock-Prediction-Models/blob/master/stacking/stack-rnn-arima-xgb.ipynb）, I can not import model in line 11. Is the file (model.py) missing?
Thank you very much!

**Comment by AlconDivino** [comment]
its a dead link

**Comment by dhaopku** [comment]
> its a dead link

Thank you AlconDivino, I don't understand very well. How to  deal with it?

**Comment by huseinzol05** [comment]
Oh, I forgot to put include it in the same folder, will done on next commit.

**Comment by dhaopku** [comment]
> Oh, I forgot to put include it in the same folder, will done on next commit.

Thank you very much.  I am looking forward to your update.

**Comment by dhaopku** [comment]
> its a dead link

In this link.   https://github.com/huseinzol05/Stock-Prediction-Models/blob/master/stacking/stack-rnn-arima-xgb.ipynb

**Comment by huseinzol05** [comment]
Fixed!
