### ISSUE TITLE
Need code to apply models on multivariate time series problems!!

### ISSUE THREAD

**Issue by Arunkumar0258** [huseinzol05/Stock-Prediction-Models#69]
Hi, Came across this amazing repository.
I am currently working on a time series problem with my own data and using your notebooks as reference. Can you please make a notebook on how to extend any of the Timeseries models for multivariate features such as Dayofweek or month or something?

Would be appreciated if that could be possible?
Thanks and Cheers :)

**Comment by Arunkumar0258** [comment]
The code is alrady working for multivariate time series problems.

**Comment by DegenRisk** [comment]
What adjustement did you make for it to work with multivariate? Was it an adjustment to the shape of the scalar function?
