### ISSUE TITLE
How to add the third parameter?

### ISSUE THREAD

**Issue by reed077** [huseinzol05/Stock-Prediction-Models#74]
I would like to add a third parameter to realtime-evolution-strategy
At now the code works with two parameters Close and Volume.
I add a third parameter for example Open
parameters = [df['Close'].tolist(), df['Volume'].tolist(), df['Open'].tolist()]
But an error occurs (ValueError: operands could not be broadcast together with shapes (1,2) (3,) (1,2))

Please tell me where else it is necessary to make changes so that the code is executed correctly.

**Comment by ycote88** [comment]
Did you find a way to do it ? Im also needing this.

**Comment by huseinzol05** [comment]
this one just need to understand my quite messy code. sorry.

**Comment by sword134** [comment]
@huseinzol05 still no update on this?
