### ISSUE TITLE
Generalization

### ISSUE THREAD

**Issue by bitnom** [huseinzol05/Stock-Prediction-Models#8]
Oh, you trained on Google trend but predict on Tesla trend. Ya, you can't. the model doesn't have a good generalization between two different trends. It need to train real time, if trained on Google, it only can predict on Google.

Maybe you can try to train more than 10 different trends, and try to predict 11th trend, let see how is good the model generalization. Never tested this theory. Problem with reinforcement learning, let say the agent trained to play DOOM shooting game. After that you put the agent on different shooting game, counter strike. Even both are shooting game, but the agent never learn how to adapt inside counter strike environment. I never saw a reinforcement learning agent able to adapt different environment to test in any research papers, correct me if I am wrong, cited with paper link.

_Originally posted by @huseinzol05 in https://github.com/huseinzol05/Stock-Prediction-Models/issues/5#issuecomment-475859801_

Referencing this reply you made, what we need now is to generalize to other datasets/timeframes. Here is a working version with parameters automatically passed: https://github.com/TensorTom/Stock-Prediction-Models/blob/master/agent/evolution-strategy-bayesian-agent.ipynb

Feel free to merge but still will be better if we can generalize.

**Comment by AlconDivino** [comment]
What exactly do you mean by generalize?

**Comment by huseinzol05** [comment]
Understood various of environments and able to survive, like Jack of all trades, master of none. It can do well but not really high score compared to an agent only trained a single trend

**Comment by bitnom** [comment]
I shouldn't have posed the issue this way. Will reopen with more specific.
