### ISSUE TITLE
"data not enough to trade"

### ISSUE THREAD

**Issue by billbarni** [huseinzol05/Stock-Prediction-Models#91]
I keep getting this error when trying to execute the realtime-agent 'stack' and running:

'http://127.0.0.1:8005/trade?data=' + followed by the data in the example

Any idea what I am doing wrong? I trained the model and saved it. But I can't understand why the data is not enough.

**Comment by IISuperluminaLII** [comment]
you need to populate the data queue for the specified window size, the trained model expects to have {window_size} amount of data_points to start trading since get_state needs window_size amount of data. append window_size amount of data and it will start trading
