### ISSUE TITLE
Can you please upgrade all your models to Tensorflow V2?

### ISSUE THREAD

**Issue by shivamtawari** [huseinzol05/Stock-Prediction-Models#92]

**Comment by oboehme89** [comment]
Hello, maybe this can help you:
https://www.tensorflow.org/guide/upgrade

It worked for me in Model 16 "attention is all you need".
Additionally I added the following two lines at the top of my code:
- tf.compat.v1.disable_v2_behavior
- tf.compat.v1.disable_eager_execution()

That made it work for me (Tensorflow Version 2-1-0)

Best regards
Oliver

**Comment by huseinzol05** [comment]
Will do, right now I am pretty busy with my company and projects, hopefully I can get back to this repo ASAP, thanks!
